#!/bin/zsh
set -euo pipefail

project_root=${0:A:h:h}
destination=${1:-"$project_root/Toolchains/bootstrap.zip"}
release_manifest=${2:-"${destination:h}/ToolchainManifest.json"}
manifest_template="$project_root/Sources/FPGAStudioCore/Resources/ToolchainManifest.json"
signing_key=${TOOLCHAIN_SIGNING_PRIVATE_KEY_FILE:-}
module_cache="$project_root/.build/module-cache"
staging=$(mktemp -d "${TMPDIR:-/tmp}/fpga-studio-toolchain.XXXXXX")
trap 'rm -rf "$staging"' EXIT

if [[ "$(uname -m)" != "arm64" ]]; then
  print -u2 "The current FPGA Studio toolchain manifest supports arm64 only."
  exit 2
fi
if [[ -z "$signing_key" || ! -f "$signing_key" ]]; then
  print -u2 "Set TOOLCHAIN_SIGNING_PRIVATE_KEY_FILE to the private key generated by scripts/toolchain-signing.swift."
  exit 2
fi

mkdir -p "$staging/bin" "$staging/lib" "$staging/share" "$staging/licenses" "$module_cache"

required_tools=(
  yosys yosys-abc nextpnr-mistral mistral-cv openFPGALoader
  iverilog vvp verilator verilator_bin
  ghdl ghdl1-llvm ghwdump
)

typeset -A prefixes
for tool in $required_tools; do
  source_path=$(command -v "$tool" || true)
  if [[ -z "$source_path" ]]; then
    print -u2 "Missing required tool: $tool"
    exit 2
  fi
  resolved_path=${source_path:A}
  cp "$resolved_path" "$staging/bin/$tool"
  chmod u+x "$staging/bin/$tool"
  prefixes[$tool]=${resolved_path:h:h}
done

copy_tree() {
  local source_path=$1
  local destination_path=$2
  [[ -d "$source_path" ]] || return 0
  mkdir -p "${destination_path:h}"
  ditto --norsrc "$source_path" "$destination_path"
}

copy_tree "$prefixes[yosys]/share/yosys" "$staging/share/yosys"
copy_tree "$prefixes[nextpnr-mistral]/share/nextpnr" "$staging/share/nextpnr"
copy_tree "$prefixes[nextpnr-mistral]/share/mistral" "$staging/share/mistral"
copy_tree "$prefixes[mistral-cv]/share/mistral" "$staging/share/mistral"
copy_tree "$prefixes[openFPGALoader]/share/openFPGALoader" "$staging/share/openFPGALoader"
copy_tree "$prefixes[openFPGALoader]/share/openfpgaloader" "$staging/share/openfpgaloader"
copy_tree "$prefixes[iverilog]/lib/ivl" "$staging/lib/ivl"
copy_tree "$prefixes[verilator]/share/verilator" "$staging/share/verilator"
copy_tree "$prefixes[ghdl]/lib/ghdl" "$staging/lib/ghdl"

# GHDL's official macOS archive resolves its private GCC runtime through @rpath.
for runtime_library in "$prefixes[ghdl]"/bin/*.dylib(N) "$prefixes[ghdl]"/lib/*.dylib(N); do
  cp "$runtime_library" "$staging/lib/${runtime_library:t}"
done

# Make Homebrew-linked Mach-O dependencies private to the archive.
# Track which source paths have been copied so the conflict check compares
# unmodified originals rather than install_name_tool-patched copies.
typeset -A copied_sources
queue=("$staging/bin"/* "$staging/lib"/*)
while (( ${#queue} )); do
  item=$queue[1]
  queue=($queue[2,-1])
  [[ -f "$item" ]] || continue
  dependencies=(${(f)"$(otool -L "$item" 2>/dev/null | tail -n +2 | awk '{print $1}')"})
  for dependency in $dependencies; do
    case "$dependency" in
      /System/*|/usr/lib/*|@*) continue ;;
    esac
    [[ -f "$dependency" ]] || continue
    dep_name=${dependency:t}
    copied="$staging/lib/$dep_name"
    if [[ -f "$copied" ]]; then
      # Same source file is fine (already copied); different source is a real conflict.
      if [[ -n "${copied_sources[$dep_name]:-}" && "${copied_sources[$dep_name]}" != "${dependency:A}" ]]; then
        if ! cmp -s "$dependency" "${copied_sources[$dep_name]}"; then
          print -u2 "Conflicting private libraries named $dep_name; refusing to make an ambiguous bundle."
          exit 2
        fi
      fi
    else
      cp "$dependency" "$copied"
      chmod u+w "$copied"
      install_name_tool -id "@rpath/$dep_name" "$copied" 2>/dev/null || true
      copied_sources[$dep_name]=${dependency:A}
      queue+=("$copied")
    fi
    install_name_tool -change "$dependency" "@executable_path/../lib/$dep_name" "$item" 2>/dev/null || true
  done
done

for label_and_tool in \
  "yosys:yosys" "nextpnr:nextpnr-mistral" "mistral:mistral-cv" \
  "openFPGALoader:openFPGALoader" "iverilog:iverilog" \
  "verilator:verilator" "ghdl:ghdl"; do
  label=${label_and_tool%%:*}
  tool=${label_and_tool#*:}
  prefix=$prefixes[$tool]
  license_files=(${(f)"$(find "$prefix" -maxdepth 2 -type f \( -iname 'LICENSE*' -o -iname 'COPYING*' \) -print 2>/dev/null)"})
  for license_file in $license_files; do
    cp "$license_file" "$staging/licenses/$label-${license_file:t}"
  done
done

# Release artifacts carry the complete repository-audited notice and license set,
# including child tools and dynamically bundled runtime libraries.
/bin/cp -X "$project_root/ThirdPartyLicenses"/* "$staging/licenses/"
cp "$project_root/THIRD_PARTY_NOTICES.md" "$staging/THIRD_PARTY_NOTICES.md"

if [[ ! -f "$staging/share/yosys/plugins/ghdl.so" ]]; then
  print -u2 "The installed Yosys does not include share/yosys/plugins/ghdl.so. Build/install ghdl-yosys-plugin before packaging."
  exit 2
fi

for item in "$staging/bin"/* "$staging/lib"/*; do
  [[ -f "$item" ]] || continue
  codesign --force --sign - "$item" 2>/dev/null || true
done

bundle_environment=(
  "PATH=$staging/bin:/usr/bin:/bin:/usr/sbin:/sbin"
  "DYLD_LIBRARY_PATH=$staging/lib"
  "YOSYS_DATDIR=$staging/share/yosys"
  "VERILATOR_ROOT=$staging/share/verilator"
  "GHDL_PREFIX=$staging/lib/ghdl"
)
smoke_source="$staging/.toolchain-smoke.v"
cp "$project_root/scripts/fixtures/toolchain-smoke/top.v" "$smoke_source"
env $bundle_environment "$staging/bin/ghdl" --version >/dev/null
env $bundle_environment "$staging/bin/iverilog" -B "$staging/lib/ivl" -V >/dev/null 2>&1
env $bundle_environment "$staging/bin/vvp" -V >/dev/null 2>&1
env $bundle_environment "$staging/bin/verilator" --version >/dev/null
env $bundle_environment "$staging/bin/yosys" -m ghdl -p "help ghdl" >/dev/null
env $bundle_environment "$staging/bin/yosys" -p "read_verilog $smoke_source; hierarchy -check -top top; synth_intel_alm -top top" >/dev/null
env $bundle_environment "$staging/bin/nextpnr-mistral" --help >/dev/null 2>&1
env $bundle_environment "$staging/bin/openFPGALoader" --help >/dev/null 2>&1
rm "$smoke_source"

cp "$manifest_template" "$staging/ToolchainManifest.json"
mkdir -p "${destination:h}" "${release_manifest:h}"
rm -f "$destination" "$release_manifest"
ditto -c -k --sequesterRsrc "$staging" "$destination"
CLANG_MODULE_CACHE_PATH="$module_cache" swift "$project_root/scripts/toolchain-signing.swift" sign \
  "$destination" "$manifest_template" "$release_manifest" "$signing_key"
CLANG_MODULE_CACHE_PATH="$module_cache" swift "$project_root/scripts/toolchain-signing.swift" verify "$destination" "$release_manifest"
print "Packaged signed bootstrap: $destination"
print "Release manifest: $release_manifest"
